version: '3.4'
services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
  certbot:
    image: certbot/certbot
